### PR TITLE
Enable setting additional HTML attributes on container

### PR DESCRIPTION
**Pull request by lustrousgorilla**

### CODE REVIEW

**Comment by geolessel** [comment]
@lustrousgorilla Thanks for the PR and I like the idea. However, before merging there are a few things that it needs before I consider it complete:

- A PR description would be helpful for future devs looking through PRs (and any looking right now)
- The change/feature isn't mentioned in the documentation. Please describe the usage there.
- From the looks of it, I think this would break the `@spec` of the function. Please update that.
- There is no accompanying test. Please add one.

**Comment by geolessel** [comment]
@lustrousgorilla I just remembered that I did some similar work in a branch here. Check out https://github.com/geolessel/react-phoenix/compare/more-options and let me know if those changes would work for you. If so, I may just open up a PR of those changes and merge that in.

**Comment by andrewmurph** [comment]
@geolessel I like those changes!

Just to check my understanding: if a target_id is given in the list of opts, are all other opts effectively redundant (as they aren't passed to the target element)?

E.g.
`react_component("test", %{}, class: "row", target_id: "test-id", style: "color:blue")`
results in 
` <div class="row" data-react-class="test" data-react-props="{}" data-react-target-id="test-id" style="color:blue"></div>"`

and then `react_phoenix.js` will render the component in the targeted `#test-id` element, leaving behind that div with the attributes from opts.

Do you think this warrants a warning / more documentation or isn't a big deal?

**Comment by lustrousgorilla** [comment]
@geolessel sorry for taking a week to reply, but yeah those changes will do the trick!

**Comment by geolessel** [comment]
Closed in favor of #45

**Pull request closed without merging**
