### PR TITLE
Update dependencies to use react-16.2.0 and react-dom-16.2.0

### PR DESCRIPTION
**Pull request by SYoung82**
We had some issues rendering various Blueprint.js Components without react and react-dom @ 16.2.0.  Request that react-phoenix dependencies be updated.

### CODE REVIEW

**Comment by geolessel** [comment]
Hmm, I'm not going to accept this PR with all the author changes in there. Beyond this, I see that you have published my JS to npm under your name:

https://registry.npmjs.org/react-phoenix

Please remove that package from npm.

Can you please explain what you are attempting to do here?

**Comment by SYoung82** [comment]
Sorry, new to the pull requests.  The npm package was in error and removed almost immediately, I believe they keep the name in the registry for a time period to ensure another package is not issued with that name.  See the 404 here, [https://www.npmjs.com/package/react-phoenix](https://www.npmjs.com/package/react-phoenix)

As for all the author changes, the intent was to just merge the first commit to change to React 16.2.  I'm simply trying to use this fork to use in my project, until the change to the React dependency is made in your repo.

Thanks for the great tool!

**Comment by scmx** [comment]
Perhaps react should be a peer dependency instead or a broader range of react versions could be allowed.

**Comment by geolessel** [comment]
React has been made a peer dependency as of v0.6.0. Thanks for the PR. Let me know if you have any issues with 0.6.0.

**Pull request closed without merging**
